# This file is based on templates provided and copyrighted by Autodesk, Inc.
# This file has been modified by Epic Games, Inc. and is subject to the license
# file included in this repository.



tk-unreal.location:
  type: github_release
  organization: ue4plugins
  repository: tk-unreal
  version: v1.1.0
