# This file is based on templates provided and copyrighted by Autodesk, Inc.
# This file has been modified by Epic Games, Inc. and is subject to the license
# file included in this repository.

includes:
- ../../app_locations.yml

settings.tk-multi-shotgunpanel.unreal:
  actions_hook: '{self}/general_actions.py:{engine}/tk-multi-shotgunpanel/tk-unreal_actions.py'
  action_mappings: {}
  enable_context_switch: true
  location: "@apps.tk-multi-shotgunpanel.location"

